[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fuzz]
runs = 1000

[invariant]
runs = 1000
depth = 25
fail_on_revert = false

[profile.default.model_checker]
contracts = {'./src/CaughtWithSymbolic.sol' = ['CaughtWithSymbolic']}
engine = 'chc' # use chc model checker
timeout = 1000
targets = ['assert'] # searches for the assert keyword
